### ISSUE TITLE
Feedback from Cran after submission attempt

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#103]
Feedback from cran:

1. Please always explain all acronyms in the description text. -> 'ADaM'; 
'CDISC'

2. Please provide a link to the used webservices (CDISC and maybe ADaM, if 
available) to the description field
of your DESCRIPTION file in the form
<http:...> or <https:...>
with angle brackets for auto-linking and no space after 'http:' and
'https:'.

3. Please write TRUE and FALSE instead of T and F. (Please don't use 'T' or 
'F' as vector names.), e.g.:
   man/app_heatmap.Rd:
     app_heatmap(
       data,
       yvar_x,
       yvar_y,
       time,
       value = "AVAL",
       cor_mthd = "pearson",
       show_sig = F,
       sig_level = 0.05
     )

4. Please add \value to .Rd files regarding exported methods and explain 
the functions results in the documentation. Please write about the 
structure of the output (class) and also what the output means. (If a 
function does not return a value, please document that too, e.g. 
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      data_to_filter.Rd: \value
      data_to_use_str.Rd: \value
      pipe.Rd: \arguments,  \value
      prep_adae.Rd: \value
      prep_adsl.Rd: \value
      pretty_IDs.Rd: \value
      run_app.Rd: \value

5. Please add small executable examples in your Rd-files to illustrate the
use of the exported function if possible.

6. You write information messages to the console that cannot be easily
suppressed. -> R/mod_popExp_line.R
It is more R like to generate objects that can be used to extract the
information a user is interested in, and then print() that object.
Instead of print()/cat() rather use message()/warning() or
if(verbose)cat(..) (or maybe stop()) if you really have to write text to
the console.
(except for print, summary, interactive functions)

7. Please make sure that you do not change the user's options, par or
working directory. If you really have to do so within functions, please
ensure with an *immediate* call of on.exit() that the settings are reset
when the function is exited. e.g.:
...
old <- options() # code line i
on.exit(options(old)) # code line i + 1
...
options(digits = 3) # somewhere after
...
e.g.: R/mod_tableGen.R
If you're not familiar with the function, please check ?on.exit. This
function makes it possible to restore options before exiting a function
even if the function breaks. Therefore it needs to be called immediately
after the option change within a function.

8. You are using installed.packages(): -> R/mod_tableGen.R
"This needs to read several files per installed package, which will be
slow on Windows and on some network-mounted file systems.
It will be slow when thousands of packages are installed, so do not use
it to find out if a named package is installed (use find.package or
system.file) nor to find out if a package is usable (call
requireNamespace or require and check the return value) nor to find
details of a small number of packages (use packageDescription)."
[installed.packages() help page]#

9. Please do not install packages in your functions, examples or vignette.
This can make the functions,examples and cran-check very slow. -> 
R/mod_tableGen.R

Please fix and resubmit.

**Comment by Jeff-Thompson12** [comment]
>

> Please always explain all acronyms in the description text. -> 'ADaM'; 'CDISC'
> 
> Please provide a link to the used webservices (CDISC and maybe ADaM, if available) to the description field of your DESCRIPTION file in the form http:... or https:... with angle brackets for auto-linking and no space after 'http:' and 'https:'.

Handful of changes made here. I don't think I input the URLs correctly. Changes pushed here: [fe17b1e](https://github.com/Biogen-Inc/tidyCDISC/pull/81/commits/fe17b1eabfb5771c8efa643f4de823ab26f5eab7)

**Comment by Jeff-Thompson12** [comment]
> Please write TRUE and FALSE instead of T and F. (Please don't use 'T' or
> 'F' as vector names.), e.g.:
> man/app_heatmap.Rd:
> app_heatmap(
> data,
> yvar_x,
> yvar_y,
> time,
> value = "AVAL",
> cor_mthd = "pearson",
> show_sig = F,
> sig_level = 0.05
> )

Changed all instances of `T` and `F` to `TRUE` and `FALSE` when appropriate. Changes pushed here: [9f7b4f3](https://github.com/Biogen-Inc/tidyCDISC/pull/81/commits/9f7b4f3e0304cc6ae4a6836657897965d4d42c62).

**Comment by Jeff-Thompson12** [comment]
> Please make sure that you do not change the user's options, par or
> working directory. If you really have to do so within functions, please
> ensure with an _immediate_ call of on.exit() that the settings are reset
> when the function is exited. e.g.:
> ...
> old <- options() # code line i
> on.exit(options(old)) # code line i + 1
> ...
> options(digits = 3) # somewhere after
> ...
> e.g.: R/mod_tableGen.R
> If you're not familiar with the function, please check ?on.exit. This
> function makes it possible to restore options before exiting a function
> even if the function breaks. Therefore it needs to be called immediately
> after the option change within a function.

Add `on.exit()` lines to reset user options in the two functions where I saw a call to `options()`. I do not think there are other instances where the user's options are changes in the application. Changes pushed here: [466217f](https://github.com/Biogen-Inc/tidyCDISC/pull/81/commits/466217fa583fde4030c4885f0d7c3147cdc5d7f1).

**Comment by Jeff-Thompson12** [comment]
> You write information messages to the console that cannot be easily
> suppressed. -> R/mod_popExp_line.R
> It is more R like to generate objects that can be used to extract the
> information a user is interested in, and then print() that object.
> Instead of print()/cat() rather use message()/warning() or
> if(verbose)cat(..) (or maybe stop()) if you really have to write text to
> the console.
> (except for print, summary, interactive functions)

There was only one function I found calling functions like `print()` or `cat()`. These calls seemed to be for debugging purposes so they were just commented out. Changes pushed here: [0cbb8b0](https://github.com/Biogen-Inc/tidyCDISC/pull/81/commits/0cbb8b05cb63ce5a6d1cb4fee04e4dcfe5531d10).

**Comment by AARON-CLARK** [comment]
Hi @Jeff-Thompson12, thanks for working on these while I was out & sorry I didn't separate them into their own issues. I simply copy/pasted the email to github on my phone since I didn't have access to a computer. Now that I'm back, I've separated out the outstanding tasks into their own issues:

- #105 
- #106 
- #107 

So I'll continue the conversation there. I did push a few commits to `for_cranny` to clean up the description slightly. I found an example of when a URL is used in the DESCRIPTION file's description field for Jenny's Brian's `googlesheets4` package. So, the angle brackets only appear to encompass the URL:

https://github.com/tidyverse/googlesheets4/blob/8257504f8353848645d925edba1b8f8c376578c9/DESCRIPTION#L10

**Comment by Jeff-Thompson12** [comment]
> I did push a few commits to `for_cranny` to clean up the description slightly. I found an example of when a URL is used in the DESCRIPTION file's description field for Jenny's Brian's `googlesheets4` package. So, the angle brackets only appear to encompass the URL:

Okay, good. I was pretty sure that needed to be cleaned up.

**Comment by AARON-CLARK** [comment]
closed with #81
