### ISSUE TITLE
Standard Tables Broken

### ISSUE THREAD

**Issue by Jeff-Thompson12** [Biogen-Inc/tidyCDISC#104]
Some of the standard tables appear to be broken now.

![image](https://user-images.githubusercontent.com/85879620/184371398-35a20b9d-f8da-40f3-847d-3f7d3b477b6b.png)

![image](https://user-images.githubusercontent.com/85879620/184371507-9348afcf-bee1-4906-84c7-8eb4146facd2.png)

**Comment by AARON-CLARK** [comment]
It looks like commit 93c84b8 is the culprit! Which means something went wrong when removing the `forcats` dependency when I was trying to replace function `varN_fctr_reorder()` with `varN_fctr_reorder2()`. Whomp whomp.
