### ISSUE TITLE
using installed.packages() & install.packages()

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#107]
> You are using installed.packages(): -> R/mod_tableGen.R "This needs to read several files per installed package, which will be slow on Windows and on some network-mounted file systems. It will be slow when thousands of packages are installed, so do not use it to find out if a named package is installed (use find.package or system.file) nor to find out if a package is usable (call requireNamespace or require and check the return value) nor to find details of a small number of packages (use packageDescription)." [installed.packages() help page]#
> 
> Please do not install packages in your functions, examples or vignette. This can make the functions,examples and cran-check very slow. -> R/mod_tableGen.R

I'm a little confused by this comment. These lines of code occur within a `glue()` function and are used to create a script for the user. As far as I'm aware we never run the lines of code. I'm not sure why it is getting flagged by CRAN. I suppose we could replace the lines of code with a `require()` for each package needed to run the script which does seem to be standard practice. What are your thoughts @AARON-CLARK?

_Originally posted by @Jeff-Thompson12 in https://github.com/Biogen-Inc/tidyCDISC/issues/103#issuecomment-1213109864_

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, yes so as you mentioned, this code doesn't ever execute but, in general, we should try to do what the CRAN team says. So let's try out an alternative method.

As for `install.packages()`, I don't think there is one, is there?

**Comment by Jeff-Thompson12** [comment]
Yes, if the package is not found, it is installed: https://github.com/Biogen-Inc/tidyCDISC/blob/8ce64ddd1024da0cd0582f5eb9472967d664a444/R/mod_tableGen.R#L749
