### ISSUE TITLE
Apply for membership to pharmaverse

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#117]
https://pharmaverse.org/contribute/lead/

**Comment by AARON-CLARK** [comment]
Will our licensing be an issue?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK, what needs to be accomplished to be able to do this?

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK, what needs to be accomplished to be able to do this?

No news yet. Will keep this GH issue informed as soon as I know.

**Comment by AARON-CLARK** [comment]
Re-pinged the council today 12/1

**Comment by AARON-CLARK** [comment]
Pinged again on 2023-01-26. As a recap, they've recently formed a "tlg & interactive tools" working group who can make decisions on inclusion of "new" packages. However, it looks like they recently updated their [the package co-lead criteria](https://pharmaverse.org/contribute/lead/), so I'll have to create more specific issues for this task.

**Comment by AARON-CLARK** [comment]
Applied the week of 2/27. See #153
