### ISSUE TITLE
Update `demo` branch with CRAN Version of tidyCDISC

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#119]

**Comment by Jeff-Thompson12** [comment]
Is there supposed to be any difference between this branch and master besides the dataset being preloaded?

**Comment by AARON-CLARK** [comment]
> Is there supposed to be any difference between this branch and master besides the dataset being preloaded?

I think it also added a google analytics tracking tag. A good way to verify would be to compare the `demo` branch vs the old master, before we added all the `for_cranny` & r cmd check stuff.

**Comment by AARON-CLARK** [comment]
closed with #129
