### ISSUE TITLE
Show protocol/studyid in a prominent way

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#131]
I think people would get a sense of security/ comfort/ affirmation if they can see the study's title in some way, as shown in this example [here](https://rconsortium.shinyapps.io/submissions-pilot2/) from the shiny4submissions task force which I just learned is using {teal} right now. 
![image](https://user-images.githubusercontent.com/17878953/193088959-4fe30210-836b-471c-948f-68931d1fee3a.png)

I know the CDISC pilot data has a studyid column in the ADSL, as seen here:
![image](https://user-images.githubusercontent.com/17878953/193100778-d37e5377-9da7-40c4-a416-896f827fc28e.png)

The ADaMIG v1.2 says that the STUDYID var is required in ADSL & BDS datasets.

**Comment by tdwils** [comment]
@AARON-CLARK  Any opinions on style or position of the Study ID?

![image](https://user-images.githubusercontent.com/16843423/209226686-3bf03819-769c-4452-8338-52f8a6bd246b.png)

![image](https://user-images.githubusercontent.com/16843423/209226736-25f72c28-f4ff-4490-9000-795a3dd58f01.png)

![image](https://user-images.githubusercontent.com/16843423/209226768-d41cecc7-66ca-4029-b59a-eab55bf9dcb8.png)

![image](https://user-images.githubusercontent.com/16843423/209226805-1d4a1956-e25b-47f6-b670-7f4ab16f88c6.png)

**Comment by AARON-CLARK** [comment]
@tdwils, that is a great question. I would use color "dimgrey" for the color so it doesn't pop too much.

Location, location, location. I could see it going a lot of places. Let's start with it right there and we can always change move it around to test new places later.

**Comment by AARON-CLARK** [comment]
closed with #146
