### ISSUE TITLE
`R-CMD-CHECK` failing; Need new release on CRAN

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#155]
The CRAN team reached out and notified me that `tidyCDISC` [is failing R-CMD-CHECK](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/tidyCDISC-00check.html) as a result of the new release of `dplyr` for the `devel` version of R. This was to be expected given #144.

So, we'll have to cut a new release of `tidyCDISC` . The `devel` branch only contains [4 changes](https://github.com/Biogen-Inc/tidyCDISC/blob/devel/NEWS.md) according to the `NEWS` file (I'll have to update), but I count these new additions too:

- adding `OS Health` & `riskmetric` badges to the `README`
- a cleaner wrapper function around the old `purrr::pmap()` that created the table generator output from the block data
- TG automatically updates the table name when a standard analysis is selected
- Got rid of the "data_from" variable from certain `selectInput()`s choices
- ATPT integration in the TG!
- Add custom footnotes
- Add default "source" and "run date" footnote
- Fixed some strange PopEx filtering issues
- Added an `app.R` file

![image](https://user-images.githubusercontent.com/17878953/215751353-95d91f4f-6d71-4556-a871-e70f94add9e9.png)

### Discussion question(s)
I think there are enough changes here to justify a minor release, incrementing from `v0.1.1` to `v0.2.0`. Or do you think  a patch release is more appropriate to `v0.1.2`?

Secondly, we have two outstanding PRs that are "close" to being ready. Do we want to include them now or later? I'm happy to wait, but wanted to ask the PR author's opinions.
* #147 
* #145

**Comment by Jeff-Thompson12** [comment]
With regards to #145, I think that should wait for the next release.

**Comment by tdwils** [comment]
#147 still needs some more work, so I would like to wait on that one too.

**Comment by AARON-CLARK** [comment]
closed with #160
