### ISSUE TITLE
Filter data is not working in Population explorer

### ISSUE THREAD

**Issue by ElijT** [Biogen-Inc/tidyCDISC#175]
I am working on TidyCDISC v0.2.0.9002 ("devel").

In the population explorer, with multiple datasets including pilot datasets, filtering the data does not work.

### Steps to replicate the issue:

> remotes::install_github("Biogen-Inc/tidyCDISC", ref = "devel")
> packageVersion("tidyCDISC") # should be v0.2.0.9002
> tidyCDISC::run_app()

Click `Use CDISC Pilot Data`

Go to "Population explorer" tab

Select x & y values (in scatter plot)

Add filter (eg. Age group) and apply filter

Color with same value as filter

### Result
![image](https://user-images.githubusercontent.com/16382466/221918779-766c22e1-03c8-479b-bf24-66ba1ca60e0b.png)

### What would be expected
I should have only one color in that situation.

I tried to remove the color labelling but it does not change anything 
There is no error message in the console
I did check at least in boxplot graph (more difficult to prove that no data is removed) but apparently the bug is also there!

**Comment by AARON-CLARK** [comment]
Hi @ElijT, this issue has been closed with the merge of #177 (Thank @Jeff-Thompson12!). Feel free to test by re-installing:
```
remotes::install_github("Biogen-Inc/tidyCDISC", ref = "devel")
packageVersion("tidyCDISC") # should be v0.2.0.9003
tidyCDISC::run_app()
```
