### ISSUE TITLE
`chevron-down` icon is not displaying

### ISSUE THREAD

**Issue by tdwils** [Biogen-Inc/tidyCDISC#183]
Message is displayed in the console about the `chevron-down` icon, and the icon is not displaying.

```
The `name` provided ('chevron-down w3-tiny') does not correspond to a known icon
```

Table Generator:

![image](https://user-images.githubusercontent.com/16843423/222543532-512d79eb-e8ea-451d-921f-f121105c7d2c.png)

Population Explorer:

![image](https://user-images.githubusercontent.com/16843423/222543666-ce3cf3d3-6774-4b3f-aba9-b0c4cc0fc3ea.png)

**Comment by AARON-CLARK** [comment]
Fixed in `devel` with commit [71f0514](https://github.com/Biogen-Inc/tidyCDISC/pull/172/commits/71f0514823b5032fed1124d2d5619973ac4201dc)
