### ISSUE TITLE
`yeti.css` takes precedence over `gt` object's font-family

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#185]
We are shooting for "times new roman" but `yeti`.css` makes heavy use of open-sans

In the app:

![image](https://user-images.githubusercontent.com/17878953/222548871-bab0986b-bddd-4b2f-8fd3-12ba760e9cf0.png)

In an html download, or when reproduced via a downloadable R script:

![image](https://user-images.githubusercontent.com/17878953/222549460-06a2890a-1142-470a-8d62-0eaedcd9b6e0.png)

**Comment by Jeff-Thompson12** [comment]
Are you guys wedded to passing the font in `gt::tab_options(table.font.names)`? It appears it is only setting a very generic CSS of `html {font-family: Times, Arial}` which is being overwritten by the `yeti.css` more specific designation of `body {font-family: ...}`.

Can easily edit in the `styles.css` file.

**Comment by tdwils** [comment]
If we leave `gt::tab_options(table.font.names)`, then the font could be passed in as a user option in the future. 

We should probably also open an issue with `gt`.

**Comment by AARON-CLARK** [comment]
closed with #186
