### ISSUE TITLE
Draft: thorough (manual) testing of `app.R` before CRAN submission

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#189]
This issue is just to build out a refined set of components to test in the app before each CRAN submission. When finalized, we'll move it over to the repo's wiki. This process may become obsolete if/when we decide to start using `shinytest2` to meet our testing needs. For now, use this rubric as a way to make sure everything is working as expected.

## Data
- [ ] Test the guide [ ❔ ] button
- [ ] test uploading data with a problem... for example, missing USUBJID
- [ ] test entire app with just one `ADSL` loaded
   - [ ] TG: see if you can still drag and drop blocks to create tables
   - [ ] TG: Create a demography table
   - [ ] TG: download an R script and run
   - [ ] PopEx: Make a graph or two - choose randomly
   - [ ] IndvEx: Test `timevis` object

## Table Generator
- [ ] Test the guide [ ❔ ] button
- [ ] test drag and drop table creation with **only one ADSL** data set uploaded
- [ ] test IDEAFilter
- [ ] test table title, footnotes
- [ ] test downloading table as HTML, CSV, and RTF
- [ ] test downloading and running an R script using...
    - [ ] CDISC pilot data
    - [ ] some other data source
- [ ] test special js stuff
    - [ ] an ADVS with ATPT present
    - [ ] several standard analyses tables
- [ ] test each stat block

## Population Explorer
- [ ] Test the guide [ ❔ ] button
- [ ] test IDEAFilter
- [ ] Test each plot and all their toggles (time consuming, yes)

## Individual Explorer
- [ ] Test the guide [ ❔ ] button for IDEAFilter
- [ ] test IDEAFilter, preferably choosing a couple different filters, one of which should be an adverse event (AEDECOD)

### Events tab
- [ ] Test the guide [ ❔ ] button
- [ ] play with each ☑️ checkbox

### Visits tab
- [ ] Test the guide [ ❔ ] button
- [ ] play with ☑️ checkboxes
- [ ] download a report in HTML and PDF

**Comment by AARON-CLARK** [comment]
@tdwils & @Jeff-Thompson12. I've been testing `tidyCDISC` today and everything seems to be fine with the exception of #192. Could you please test `devel` and let me know if you experience / find any issues? I'd like to get this merged with `master` as soon so I can push the changes to CRAN. Any help with #192 is also greatly appreciated. Thanks!

**Comment by tdwils** [comment]
I have a few comments/questions about the testing checklist above:

> test uploading data with a problem... for example, missing USUBJID
-	Can we create test datasets with these characteristics and store them someplace for easy testing?

> test entire app with just one ADSL loaded
-	Not all of the tests below would be applicable. Can we narrow it down to a list of relevant items? Are there areas where problems would be expected?

> test drag and drop table creation with only one ADSL data set uploaded
-	What is the expected behavior? Should we test specific combinations of variables/stats?

> Test the guide [ ❔ ] button
-	Add this under “Population Filter / Visits tab” also.

**Comment by AARON-CLARK** [comment]
Thanks @tdwils! Here are some of my comments.

> > test uploading data with a problem... for example, missing USUBJID
> 
> * Can we create test datasets with these characteristics and store them someplace for easy testing?

Yes, we can! See #197

> 
> > test entire app with just one ADSL loaded
> 
> * Not all of the tests below would be applicable. Can we narrow it down to a list of relevant items? Are there areas where problems would be expected?

Good idea. I've edited the original task list above.


> > test drag and drop table creation with only one ADSL data set uploaded
> 
> * What is the expected behavior? Should we test specific combinations of variables/stats?

No specific combination of var and stat blocks are required. Its all too easy to make an accident in the js code that messes with the drag and drop capability of the table. So if you can create one basic table, this task is complete.


> > Test the guide [ ❔ ] button
> 
> * Add this under “Population Filter / Visits tab” also.

Done.

**Comment by AARON-CLARK** [comment]
Added this checklist to [the repo's wiki](https://github.com/Biogen-Inc/tidyCDISC/wiki/Thorough-testing-of-app-prior-to-release).
