### ISSUE TITLE
R script path object name issues when not using CDISC pilot data

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#198]
@AARON-CLARK I'm going through the checklist, and I'll post my comments when I finish. But I just want to point out one issue I have found when using study data (not CDISC). The variables `filenames` and `file_names` are both being used, but I think they should be the same

The Shiny app code

https://github.com/Biogen-Inc/tidyCDISC/blob/71f0514823b5032fed1124d2d5619973ac4201dc/R/mod_tableGen.R#L745-L756

produces this script, 

![image](https://user-images.githubusercontent.com/16843423/223546750-f5b1da44-710f-4526-b77c-a771da7b670d.png)

which gives an error because of the variable name:

![image](https://user-images.githubusercontent.com/16843423/223546848-fa7fc946-f3b5-484f-afcd-2fea33f76d8b.png)

There is the same issue with the variables `study_dir` and `study_directory`. The variable names should be the same:

![image](https://user-images.githubusercontent.com/16843423/223549575-b577c0b9-6711-4254-bb1f-f3095a56380c.png)

_Originally posted by @tdwils in https://github.com/Biogen-Inc/tidyCDISC/issues/172#issuecomment-1458843091_

**Comment by tdwils** [comment]
@AARON-CLARK & @Jeff-Thompson12  I am testing the script generated by tidyCDISC, and I get an error when it tries to install the latest version of tidyCDISC:

```
>   remotes::install_github('Biogen-Inc/tidyCDISC')
Downloading GitHub repo Biogen-Inc/tidyCDISC@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/Biogen-Inc/tidyCDISC/tarball/HEAD' failed
```

According to this: https://stackoverflow.com/questions/65421798/devtoolsinstall-github-failing-in-r4-0-03#:~:text=Turns%20out%20that%20this%20problem%20was%20caused%20by,is%20a%20default%2060%20second%20timeout%20for%20install_github. , the timeout needs to be increased.

Are you familiar with this?

**Comment by Jeff-Thompson12** [comment]
> According to this: https://stackoverflow.com/questions/65421798/devtoolsinstall-github-failing-in-r4-0-03#:~:text=Turns%20out%20that%20this%20problem%20was%20caused%20by,is%20a%20default%2060%20second%20timeout%20for%20install_github. , the timeout needs to be increased.
> 
> Are you familiar with this?

No, I have not come across this issue before.
