### ISSUE TITLE
App issues with latest pkgs

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#202]
## Test Branch
I created a [new branch](https://github.com/Biogen-Inc/tidyCDISC/pull/204) called `latest_r_and_pkgs_20230301` if you want to test the behaviors noted below. Basically, it just updates the `renv.lock` file using `renv::update()`.

## Issues

I updated all packages to the latest versions and went through the checklist again (well, most of it). Here are some things I found:

- [x] **Item 1**

(latest versions of all packages)

Used CDISC data to generate Table 18 (Overall summary of AEs):

```
Warning: Specifying the `id_cols` argument by position was deprecated in tidyr 1.3.0.
ℹ Please explicitly name `id_cols`, like `id_cols = AOCCFL`.
```

- [ ] **Item 2**

(latest versions of all packages)

Used study data. Loaded ADSL dataset. Attempted to create “Table3 Accounting of subjects”.

![image](https://user-images.githubusercontent.com/16843423/223753659-5a2fb57a-ae5a-47f0-9ee0-26cb45107660.png)

```
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
```

This also happens if you try to generate “Table 5: Demography” and filter by ACTARM.

- [ ] **Item 3**

(latest versions of all packages) 

Individual Explorer: The guide button [ ? ] (in the Filter by Patient Number box) does not work like the other guide buttons. You have to click on the solid color within the square in order for it to work. If you click on the question mark, then nothing happens.

- [ ] **Item 4**

(latest versions of all packages)

A lot more messages are getting printed to the console when the app is run:

![image](https://user-images.githubusercontent.com/16843423/223753712-48f2a7f3-d194-40bd-95fb-07580cc1c7dd.png)

- [ ] **Item 5**

(latest versions of all packages)

In the Population Explorer with CDISC data:

![image](https://user-images.githubusercontent.com/16843423/223753762-6a464b2d-1b88-4d3e-ab7c-9ea8048509e5.png)

The graph generates successfully, but this error is in the Console:

```
Warning: Error in vectbl_as_col_location2: Can't extract column with `value_y`.
✖ Subscript `value_y` must be size 1, not 0.
  155: <Anonymous>
  154: signalCondition
  153: signal_abort
  152: cnd_signal
  151: <Anonymous>
  139: eval
  138: eval
  137: .transformer
  135: <Anonymous>
  111: plotly::ggplotly
  109: %||%
  106: modify_list
  105: config
  103: renderPlotly [C:/Users/twilson4/Documents/RProjects_laptop/tidyCDISC/R/mod_popExp.R#274]
  102: func
   99: shinyRenderWidget
   98: func
   85: renderFunc
   84: output$popExp_ui_1-plot_output
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

- [ ] **Item 6**

(latest versions of all packages)

CDISC data, Individual Explorer, Visits tab. Click on Milestones or Adverse Events checkbox:

```
Warning: Unknown columns: `ATM`
Warning in ggplot2::geom_vline(data = vline_dat, ggplot2::aes(xintercept = !!INPUT_visit_var,  :
  Ignoring unknown aesthetics: text
Warning: Unknown columns: `ATM
```

_Originally posted by @tdwils in https://github.com/Biogen-Inc/tidyCDISC/issues/172#issuecomment-1460330255_

**Comment by Jeff-Thompson12** [comment]
> **Item 2** (latest versions of all packages)
> 
> Used study data. Loaded ADSL dataset. Attempted to create “Table3 Accounting of subjects”.
> 
> ![image](https://user-images.githubusercontent.com/16843423/223753659-5a2fb57a-ae5a-47f0-9ee0-26cb45107660.png)
> 
> ```
> Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
> ```
> 
> This also happens if you try to generate “Table 5: Demography” and filter by ACTARM.

This appears to be a result of using `stop()` instead of `validate()`.

**Comment by tdwils** [comment]
Regarding **Item 4**, I think this is a change coming from `shiny` version 1.7.2. That version has this change:

> Closed #3250:{rlang}/{tidyeval} conditions (i.e., warnings and errors) are no longer filtered from stack traces. (#3602)

It has made the stack trace more verbose. I tested this by using the lock file from the `devel` branch and updating only `shiny` to v1.7.2. The additional messages appeared in the console when an error was forced.

In `run_dev.R` we already have `options(shiny.fullstacktrace = FALSE)`, but it doesn’t seem to affect these messages.

Maybe someone else can look at it so see if there is a way to go back to the less verbose version.

**Comment by tdwils** [comment]
> **Item 3**
> (latest versions of all packages)
>
> Individual Explorer: The guide button [ ? ] (in the Filter by Patient Number box) does not work like the other guide buttons. You have to click on the solid color within the square in order for it to work. If you click on the question mark, then nothing happens.

This behavior happens when you run the app in the RStudio browser rather than the web browser. See  #179 for another example of a difference in behavior between the two browsers.

**Comment by AARON-CLARK** [comment]
Closing Since separate issues created for each **item** above.
