### ISSUE TITLE
TG: stop() or validate() ?

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#206]
**Item 2** (latest versions of all packages)
> 
> Used study data. Loaded ADSL dataset. Attempted to create “Table3 Accounting of subjects”.
> 
> ![image](https://user-images.githubusercontent.com/16843423/223753659-5a2fb57a-ae5a-47f0-9ee0-26cb45107660.png)
> 
> ```
> Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
> ```
> 
> This also happens if you try to generate “Table 5: Demography” and filter by ACTARM.

This appears to be a result of using `stop()` instead of `validate()`.

_Originally posted by @Jeff-Thompson12 in https://github.com/Biogen-Inc/tidyCDISC/issues/202#issuecomment-1460896576_

**Comment by Jeff-Thompson12** [comment]
It appears what was happening here has to do with `rlang_error` class objects. They are lists and `asJSON()` was no longer handling them in the expected way.

**Comment by AARON-CLARK** [comment]
closed wtih #213
