### ISSUE TITLE
Lots of new messaging in the console, perhaps shiny version related

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#207]
**Item 4**
(latest versions of all packages)

A lot more messages are getting printed to the console when the app is run:

![image](https://user-images.githubusercontent.com/16843423/223753712-48f2a7f3-d194-40bd-95fb-07580cc1c7dd.png)

Regarding **Item 4**, I think this is a change coming from `shiny` version 1.7.2. That version has this change:

> Closed #3250:{rlang}/{tidyeval} conditions (i.e., warnings and errors) are no longer filtered from stack traces. (#3602)

It has made the stack trace more verbose. I tested this by using the lock file from the `devel` branch and updating only `shiny` to v1.7.2. The additional messages appeared in the console when an error was forced.

In `run_dev.R` we already have `options(shiny.fullstacktrace = FALSE)`, but it doesn’t seem to affect these messages.

Maybe someone else can look at it so see if there is a way to go back to the less verbose version.

**Comment by AARON-CLARK** [comment]
@tdwils, I played around in the app for a while and was not able to reproduce. Can you tell us a specific action in the app to generate one of these errors. I'm using the current `devel` branch, which has the following pkg versions:

![image](https://user-images.githubusercontent.com/17878953/225301126-2910cbc0-5404-4507-b81a-485051e15235.png)

**Comment by tdwils** [comment]
Yes, they were occurring in the TG. I tried it just now, and the messages are gone.
