### ISSUE TITLE
Save Uploaded Data

### ISSUE THREAD

**Issue by TYoungTradeCraft** [Biogen-Inc/tidyCDISC#248]
Is there any way within tidyCDISC to save my studies datasets that I have uploaded so that I don’t have to do a “Data Upload” each time I run tidyCDISC?

**Comment by AARON-CLARK** [comment]
Hi @TYoungTradeCraft, this feature could be solved with #223. In the meantime, I'll close this issue as a duplicate, but #223 should start development soon. Sorry for the delay in getting back to you!
