### ISSUE TITLE
[Question] Do the confidence intervals address repeated measures?

### ISSUE THREAD

**Issue by adrianolszewski** [Biogen-Inc/tidyCDISC#250]
Dear Authors,
First of all I wanted to say I admire your work and congratulate you an excellent idea for the exploration of CDISC datasets!

I have question about these CIs:
![obraz](https://github.com/Biogen-Inc/tidyCDISC/assets/95669100/9fbd960a-365b-4233-bb0b-b683ea3f795a)

Are they just raw, "naive" unpaired CI for the mean, or do you maybe employ the MMRM or LMM (if so, then how parameterized) to reflect the fact they come from observations repeated over time (so likely correlated within-patient)? In the free time I will look at the code, but just wanted to ask quickly in the move.

**Comment by aclark02-arcus** [comment]
Hi @adrianolszewski. Thanks for opening an issue to ask this question. I've identified the code that produces the 95% CI's for the line plot module here:

https://github.com/Biogen-Inc/tidyCDISC/blob/f41ed77e1fd0df86ad95ec75dbb01efa565d00af/R/mod_popExp_line.R#L204

As you can see, it leverages a "naive" approach.
