### ISSUE TITLE
Issues loading non-ADSL datasets

### ISSUE THREAD

**Issue by zgweeaxe** [Biogen-Inc/tidyCDISC#27]
Hello,
has there been already some feedback from other users implementing tidyCDISC? I tried it with CDISC data of several different studies and can always only load the ADSL. Every other dataset results in "Can't establish connection". 
I'm trying to get to the bottom of it but I was interestd if there has been similar feedback/isues from other users?
Greets

**Comment by AARON-CLARK** [comment]
Hi @zgweeaxe,

You are the first to report any potential issue regarding failure to load non-ADSL data. I curious of the following:

1. Can you click the 'Use CDISC Pilot Data' Button without error? If you click it, it will load 4 ADaM datasets.
![image](https://user-images.githubusercontent.com/17878953/106748758-aa16a080-65f3-11eb-8f0f-9e3d03194065.png)

2. What other ADaMs are you trying to upload? Have you tried other ADaM files? As a test this morning, I successfully loaded an ADSL, ADAE, and ADMH:
![image](https://user-images.githubusercontent.com/17878953/106749036-0b3e7400-65f4-11eb-979a-37282123fc64.png)

3. Have you changed the code at all?

**Comment by zgweeaxe** [comment]
Hi Aaron,
yes I can use the example Files. There seems to be no problem.
I tried several different ADaM Files from different projects. These were also validated and should be consistent with CDISC.

I did not change the code at all. 
But I have to say that I had some troubles identifiying and installing all relevant packages, as I tried it out on a new machnine without any prior R installation.

**Comment by AARON-CLARK** [comment]
> I had some troubles identifiying and installing all relevant packages

I see. Out of curiosity, what R packages gave you issues?

Were you able to build the `tidyCDISC` package successfully by running [this code](https://github.com/Biogen-Inc/tidyCDISC#use-case)?

**Comment by zgweeaxe** [comment]
The problem was that I tried working driectly from the Code files from the Github page. This was a bit difficult as it required RTools with which I was not familiar
With the code that you pasted, I was able to directly install tidyCDISC. 

I could not run 
`golem::document_and_reload()`
as this returnes:
> Error : No root directory found in C:/Users/zgweeaxe/Documents or its parent directories. Root criterion: contains a file "DESCRIPTION"

when running the app via run_app() and trying to load something else than ADSL I get following in the Log

`> run_app()
Lade nötiges Paket: shiny

Listening on http://127.0.0.1:6301
Warnung in structure(d <- filter_returns[[utils::tail(filters(), 1)]]$data(), 
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warnung: The select input "selPatNo" contains a large number of options; consider using server-side selectize for massively improved performance. See the Details section of the ?selectizeInput help topic.
Warnung in file(con, "rb")
  kann Datei 'inst/app/www/red_x.png' nicht öffnen: No such file or directory
Warnung: Error in file: kann Verbindung nicht öffnen
  [No stack trace available]`

**Comment by AARON-CLARK** [comment]
Hmmm, it looks like you are missing files which likely has something to do with how you were accessing them through github. I would recommend downloading this package's code into a new R project according to [this guide](https://happygitwithr.com/new-github-first.html#new-rstudio-project-via-git) from the `happy git` book. The git URL is located here:

![image](https://user-images.githubusercontent.com/17878953/106899113-f846a500-66c2-11eb-8193-81a394d7359e.png)

https://github.com/Biogen-Inc/tidyCDISC.git

Let me know if you have any other issues and I'll re-open!

**Comment by zgweeaxe** [comment]
Dear Aaron, 
yes that did help! Thanks for the support.
The problem was that the "Error Window" did not show the problem before. Now it spcifies the issue. 
TidyCDISC misses the variables AVISIT, AVISITN, VISIT, BASE, CHG. After adding these as Dummy Variables to my datasets, they could be loaded!
I am now just a bit confused, as these are per CDISC not required for BDS but only Permissible. 
Thanks again for the great help and publishing of this tool!

**Comment by AARON-CLARK** [comment]
> I am now just a bit confused, as these are per CDISC not required for BDS but only Permissible.

Hi @zgweeaxe, you are correct in that they are only permissible. However, a high percentage of BDS tables contain these variables, so we designed the app to depend on their existence in the users' data. Your work-around (creating dummy columns) is sufficient. Glad you got it working!
