### ISSUE TITLE
Create `Source` and `Run Date` footnote

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#41]
Example:

![source and run date](https://user-images.githubusercontent.com/17878953/155714805-2f46d8ad-e7eb-4c19-9607-377761778c1d.png)

**Comment by AARON-CLARK** [comment]
At the very least, we can include a "Run Date" footnote by default in the app. Source doesn't make sense until the R script is produced locally. I suppose in the application, Source could just contain a placeholder like: "tidyCDISC app".

**Comment by Jeff-Thompson12** [comment]
Feature incorporated in #123
