### ISSUE TITLE
Create cleaner wrapper function around purrr::pmap() that creates table

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#47]
The idea is to make this function more user friendly so it can be used outside of the app easily. [Here](https://github.biogen.com/biometrics/SEER/blob/542d92fb90168749aa45e716498439c27f26a9ba/R/mod_tableGen.R#L842) is the section of code I'm talking about... which gets' called in 3 different places.

**Comment by Jeff-Thompson12** [comment]
I'm going to expand this to more generally cleaning up the R Script

**Comment by Jeff-Thompson12** [comment]
Improvement incorporated in #123
