### ISSUE TITLE
error message after uploaded ADSL dataset.

### ISSUE THREAD

**Issue by zunqiu** [Biogen-Inc/tidyCDISC#57]
Hello,

I uploaded my ADSL in my local Rstudio environment for this app. however, I got error message. I do have usubjid variable in the dataset. Could you please help to identify the issue? Thank you very much
![Capture1](https://user-images.githubusercontent.com/19319042/157320969-f984fb8f-a92c-4245-9e7c-9fbc69b4208b.PNG)
!

**Comment by AARON-CLARK** [comment]
Hi @zunqiu,

I've never seen that error message before, so I have a couple questions for you. Did you fork the repo and change any of the app's code? If so, send me the repo. OR did you just install `tidyCDISC` from Github and run: `tidyCDISC::run_app()` to launch the app?

Second question: are there any additional messages in the console? If so, paste them here. If not, perhaps try this to reveal more helpful messages:
```
options(shiny.fullstacktrace = TRUE)
tidyCDISC::run_app()
```

There are actually a decent amount of data compliance checks going on behind the scenes, so it sounds like your data passed those initial tests. I'd really be interested to know what's "wrong" with your data that it could break the table generator! `USUBJID` has legitimate values in the column?

**Comment by zunqiu** [comment]
Hi Aaron,
Thanks for your message. Here are my answers: 
1. I used tidyCDISC::run_app() to launch the app on my local Rstudio.
2. Here are additional messages in the console after I used the options you provided.



 144: h  143: .handleSimpleError  142: stop  141: tippy  140: dots_list  139: tags$li  138: FUN  137: apply  136: purrr::map  135: %>%  134: rowBlock  133: dots_list  132: tags$ul  131: dots_list  130: div  129: dots_list  128: div  127: dots_list  126: div  125: .f  124: purrr::map2  123: purrr::map  122: %>%  121: rowPallete  120: dots_list  119: div  118: column  117: rowArea  116: <reactive>  115: ..stacktraceon..  114: .func  113: withVisible  112: withCallingHandlers  111: contextFunc  110: env$runWith  109: force  108: domain$wrapSync  107: promises::with_promise_domain  106: withReactiveDomain  105: domain$wrapSync  104: promises::with_promise_domain  103: ctx$run  102: self$.updateValue  101: ..stacktraceoff..  100: table_generator   99: renderUI   98: func   97: force   96: withVisible   95: withCallingHandlers   94: domain$wrapSync   93: promises::with_promise_domain   92: captureStackTraces   91: doTryCatch   90: tryCatchOne   89: tryCatchList   88: tryCatch   87: do   86: hybrid_chain   85: renderFunc   84: output$all_rows   83: ..stacktraceon..   82: orig   81: func   80: withCallingHandlers   79: domain$wrapSync   78: promises::with_promise_domain   77: captureStackTraces   76: withCallingHandlers   75: shinyCallingHandlers   74: force   73: domain$wrapSync   72: promises::with_promise_domain   71: private$withCurrentOutput   70: force   69: withVisible   68: withCallingHandlers   67: domain$wrapSync   66: promises::with_promise_domain   65: captureStackTraces   64: doTryCatch   63: tryCatchOne   62: tryCatchList   61: tryCatch   60: do   59: hybrid_chain   58: force   57: withVisible   56: withCallingHandlers   55: domain$wrapSync   54: promises::with_promise_domain   53: captureStackTraces   52: doTryCatch   51: tryCatchOne   50: tryCatchList   49: tryCatch   48: do   47: hybrid_chain   46: observe   45: <observer:output$all_rows>   44: contextFunc   43: env$runWith   42: force   41: domain$wrapSync   40: promises::with_promise_domain   39: withReactiveDomain   38: domain$wrapSync   37: promises::with_promise_domain   36: ctx$run   35: run   34: withCallingHandlers   33: domain$wrapSync   32: promises::with_promise_domain   31: captureStackTraces   30: withCallingHandlers   29: shinyCallingHandlers   28: force   27: withVisible   26: withCallingHandlers   25: domain$wrapSync   24: promises::with_promise_domain   23: captureStackTraces   22: doTryCatch   21: tryCatchOne   20: tryCatchList   19: tryCatch   18: do   17: hybrid_chain   16: flushCallback   15: FUN   14: lapply   13: ctx$executeFlushCallbacks   12: .getReactiveEnvironment()$flush   11: flushReact   10: serviceApp    9: ..stacktracefloor..    8: withCallingHandlers    7: domain$wrapSync    6: promises::with_promise_domain    5: captureStackTraces    4: ..stacktraceoff..    3: runApp    2: print.shiny.appobj    1: <Anonymous>
Here is how the uploaded data looks  in the app 


Please let me know if you need anything else to identify the situation. I look forward to hearing from you again.
Thank you very much for your help!
BestZunqiu

    On Tuesday, March 8, 2022, 12:56:40 PM PST, Aaron Clark ***@***.***> wrote:  
 
 


Hi @zunqiu,

I've never seen that error message before, so I have a couple questions for you. Did you fork the repo and change any of the app's code? If so, send me the repo. OR did you just install tidyCDISC from Github and run: tidyCDISC::run_app() to launch the app?

Second question: are there any additional messages in the console? If so, paste them here. If not, perhaps try this to reveal more helpful messages:
options(shiny.fullstacktrace = TRUE)
tidyCDISC::run_app()

There are actually a decent amount of data compliance checks going on behind the scenes, so it sounds like your data passed those initial tests. I'd really be interested to know what's "wrong" with your data that it could break the table generator! USUBJID has legitimate values in the column?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AARON-CLARK** [comment]
Thanks for the snapshot! Is your data (pasted image below) looks... peculiar. Are you missing `USUBJID`s plus other other variables?

![image](https://user-images.githubusercontent.com/19319042/157348271-6c215f49-d36b-4eda-8aa6-bfa38df97cbd.png)

**Comment by zunqiu** [comment]
Hi Aaron,
I removed all data values from it. I do have all values under each column. I just particularly show the format of the "usubjid" in case you need to check.



ThanksEric    On Friday, March 11, 2022, 01:55:06 PM PST, Aaron Clark ***@***.***> wrote:  
 
 


Thanks for the snapshot! Is your data (pasted image below) looks... peculiar. Are you missing USUBJIDs plus other other variables?



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AARON-CLARK** [comment]
Hi @zunqiu,

I just tested the application on about 13 randomly selected `ADSL`s from my organization and couldn't replicate your issue, so I'm starting to run out of ideas on how to debug. I wish the output you gave me was more clear. Oh well, that's not your fault. Perhaps try comparing the CDISC Pilot data's `ADSL` to your own to look for differences:
```
# Read in ADSLs
pilot_adsl <- tidyCDISC::adsl
my_adsl <- haven::read_sas("path/to/my/data/adsl.sas7bdat")

# Compare column classes for any mismatches
janitor::compare_df_cols(pilot_adsl, my_adsl, return = "mismatch")

# visually inspect for noticable differences
View(pilot_adsl)
View(my_adsl)
```
If that doesn't reveal any obvious differences, perhaps try a different study's `ADSL` in the app to see if you get similar results. Let me know how it goes!

**Comment by AARON-CLARK** [comment]
@zunqiu, another option: try uploading an `ADSL` + some other ADaM dataset, like an `ADAE`. Sometimes the app performs differently MORE than just a single `ADSL` is loaded.

**Comment by AARON-CLARK** [comment]
Hi @zunqiu, can you also run `sessionInfo()` in your R session so I can understand the context of your R environment and associated packages?

**Comment by zunqiu** [comment]
Hi Aaron,
Thanks for your message. I have not got chance to compare the ADSL yet. I will do it this week. here is the sessionInfo() I have



ThanksZunqiu



    On Monday, March 21, 2022, 08:47:22 AM PDT, Aaron Clark ***@***.***> wrote:  
 
 


Hi @zunqiu, can you also run sessionInfo() in your R session so I can understand the context of your R environment and associated packages?

**Comment by zunqiu** [comment]
Thanks for your message. I have not got chance to compare the ADSL yet. I will do it this week. here is the sessionInfo() I hav
![sessionInfo](https://user-images.githubusercontent.com/19319042/159300768-ea86f683-8540-49c2-9900-427fe33c6f8b.png)
e

**Comment by zunqiu** [comment]
Hi Aaron,

I think it may relate to R environment because it gives me error even I just use your demo data now. Also, I compared the ADSL data. there is no alarm messages. 

![image](https://user-images.githubusercontent.com/19319042/159332546-1f8bb6b0-1556-40b3-87df-5bf8fca1a9d6.png)

Here is the screenshot when I use the demo data. 

![image](https://user-images.githubusercontent.com/19319042/159332651-b4fdf3f7-e1c4-4a19-affb-6692261ff74b.png)

you see that the second tab gives me the error message as I was using my own dataset. 
![image](https://user-images.githubusercontent.com/19319042/159332748-530fba2a-cd86-4d99-9a57-04a4ace7298a.png)


So, I am wondering if it is my environment to cause the reproducibility fail...

Thanks
Zunqiu

**Comment by AARON-CLARK** [comment]
Hi @zunqiu. First, thank you for all the diagnostic information! That was extremely helpful to track down this bug. With my [latest commit](https://github.com/Biogen-Inc/tidyCDISC/commit/83dda5c6940f9920dc5db81c36fccce597f5e917) I was able to resolve this issue.

Previously, the `tidyCDISC` package relied on the current CRAN release `v0.1.0`, which had the following `tippy()` arguments:

![image](https://user-images.githubusercontent.com/17878953/159766830-93254dc4-2905-4dad-8365-ab418a44126b.png)

However, you were using the dev version: `tippy 1.0.0`, which relies on a renamed tooltip argument called "content", hence the message: "Error: must pass content". 

![image](https://user-images.githubusercontent.com/17878953/159767478-4c83c5e4-527c-45ee-bc6d-f2430cdf05dd.png)

After playing around with the dev release of `tippy`, I found it to be much more user friendly and provide noticeable improvements to the Table Generator's user interface, so  `tidyCDISC` should also rely on dev `tippy 1.0.0`.

If you re-install `tidyCDISC` using `remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("Biogen-Inc/tidyCDISC")`, your application should work as expected. Please see the `tidyCDISC` [v0.0.3](https://github.com/Biogen-Inc/tidyCDISC/releases/tag/v0.0.3) for more details & notes on the changes you'll notice in the application.

**Comment by zunqiu** [comment]
Thanks Aaron! It is working now!
