### ISSUE TITLE
Rcheck: Note - too many package dependencies

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#62]
![image](https://user-images.githubusercontent.com/17878953/157322091-2efdfe5c-b917-4666-a21f-7a50be937cdb.png)

**Comment by AARON-CLARK** [comment]
Got it down to 35 dependencies

**Comment by AARON-CLARK** [comment]
Removed two more: `RColorBrewer` and `forcats`. I could probably remove `broom` and maybe `tibble`???

**Comment by AARON-CLARK** [comment]
`magrittr` removed in this [commit](https://github.com/Biogen-Inc/tidyCDISC/pull/81/commits/433c1b6f4c1154edcd5609d727fbcbc79f335d9c). It was only importing the pipe operator, which was redundant since we get that for "free" from `dplyr`.

**Comment by AARON-CLARK** [comment]
`tidyselect` removed in this commit:L [4bec59b](https://github.com/Biogen-Inc/tidyCDISC/pull/81/commits/4bec59b81c1195796bcaf35e6b935337a16cf45e). It was only being used for `any_of()` which we also get for "free" from `dplyr`.

**Comment by AARON-CLARK** [comment]
Looking at the `NAMESPACE` file, I'm wondering if we can get rid of...

* `data.table`. There are only two functions used that we may be able to find elsewhere, or find an alternative.
![image](https://user-images.githubusercontent.com/17878953/174126942-86b1f5f4-cf83-4269-8bbb-d6e49faa1c90.png)


* `htmltools`. All of these functions exist in the `shiny` package, do they not? I'm not sure if they do exactly the same thing though... but assume that they might? 
![image](https://user-images.githubusercontent.com/17878953/174126846-5790267b-7dfc-42d7-bf30-1540500c9fb9.png)

* `stringi`... not sure if these have replacements elsewhere... or can be "recreated" using `stringr` functions?
![image](https://user-images.githubusercontent.com/17878953/174127315-a0c8203e-b16d-435c-b37c-2f2b65a532aa.png)


* `tippy`... isn't there other packages that do this? Does shiny handle this at all?
![image](https://user-images.githubusercontent.com/17878953/174127213-67dd1182-b0ff-4cf7-a715-c23accce1097.png)

Do you have any thoughts/comments @Jeff-Thompson12?

**Comment by Jeff-Thompson12** [comment]
Yeah, let me more fully look into. It does appear that `{shiny}` is exporting those function from `{htmltools}` at least.

For instance
> shiny::HTML
function (text, ..., .noWS = NULL) 
{
    htmlText <- c(text, as.character(dots_list(...)))
    htmlText <- paste8(htmlText, collapse = " ")
    attr(htmlText, "html") <- TRUE
    attr(htmlText, "noWS") <- .noWS
    class(htmlText) <- c("html", "character")
    htmlText
}
<bytecode: 0x000002b24b6b9ff8>
**<environment: namespace:htmltools>**

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK the replacement of `{stringi}` and `{htmltools}` seems fine, but I don't think it's advisable to remove `{tippy}` and removing `{data.table}` seems questionable.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, I agree regarding `{tippy}`.

Update on `{data.table}`: `setDT` isn't being used anymore. I forgot to remove it from the `@importFrom` statement somewhere. However, I found `data.table::transpose()` was being used somewhere else. I'm assuming we could swap that out, so the big one is `rbindlist()` if we can an alternative.

![image](https://user-images.githubusercontent.com/17878953/174300438-ffbe4174-6273-425d-a156-3d980ab588c8.png)

**Comment by Jeff-Thompson12** [comment]
Well there is this:
![image](https://user-images.githubusercontent.com/85879620/174301029-f4bf949c-bdbd-4be8-aadd-95de0058f3bb.png)

**Comment by Jeff-Thompson12** [comment]
Maybe this is an instance where we move `{data.table}` to Suggests

**Comment by AARON-CLARK** [comment]
> Maybe this is an instance where we move `{data.table}` to Suggests

Oh interesting, I've never set up an R package to conditionally use a dependency. I'm game. If it's easy enough, I'd love to do the same for `{data.table}` & `{forcats}`. I revamped a function used by the table generator when removing `{forcats}` that was much faster than my new solution.

**Comment by Jeff-Thompson12** [comment]
I'm going to look into. These are probably good candidates for it. Either add nice but not necessary features or improve compiling time.

I can focuse on `{data.table}` and `{tippy}` if you want to look at `{forcats}`.

**Comment by Jeff-Thompson12** [comment]
I will work on `{data.table}` first. I was just thinking that all we are using `{tippy}` for is to add tooltips which amounts mostly to descriptive text. While this is nice, it is not necessary for the application to function, so it seems like a good candidate to add to `Suggests`

**Comment by AARON-CLARK** [comment]
Let's hold off on adding `{tippy}` to `Suggests` field just yet. Even though it has a small presence in the package, it adds the SAS labels to variable names on the table generator, which is HUGE. It also helps explain the STAT blocks which is vital when you don't have the user guide open. I don't think the table generator would be as easy to understand without them, so I don't want to sacrifice that user-friendliness.

**Comment by AARON-CLARK** [comment]
On that note, I think the table generator could use an overhaul to the UI, as noted #37, which may decrease the need for tooltips.

**Comment by AARON-CLARK** [comment]
closed with #81
