### ISSUE TITLE
Rcheck: N fnIndvExplVisits: no visible binding for `<<-` assignment to 'avals_by'

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#71]
Just a note:

![image](https://user-images.githubusercontent.com/17878953/170262445-29be8c5b-4e72-4ed2-9de5-a09473adab06.png)

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK 
Is `deliver_avals_by()` a failed attempt at correcting this issue? I don't see it actually being used in the code.

**Comment by AARON-CLARK** [comment]
> Is `deliver_avals_by()` a failed attempt at correcting this issue? I don't see it actually being used in the code.

Hi @Jeff-Thompson12. Yes, it's commented out in commit 848a961d9890c9bc6a820f9041cddfd7a0dfe8e2, but only because I tested it (along with a bunch of other ideas) and it didn't work as expected.

**Comment by Jeff-Thompson12** [comment]
Cool, I'm going to remove it from the branch I'm working on in that case.

Also, I do not see why `avals_by` is a global variable or why we would even need to use `<<-` instead of just `<-`. The only thing I could figure is that there are multiple incidences of the module being called and all need to be using the same value for `avals_by`, but that doesn't seem to be the case either.

Am I missing something obvious here?

**Comment by AARON-CLARK** [comment]
> I do not see why `avals_by` is a global variable or why we would even need to use `<<-` instead of just `<-`.

@Jeff-Thompson12, that is a great question! It's been a while since I've followed the logic behind this plotting function. So when it came up as a NOTE in `rcmdcheck()` I just assume it needed to be maintained in the parent.frame(). However, I don't know if that's necessarily true. Have you tested swapping `<<-` for `<-`? If so, what happened?

**Comment by Jeff-Thompson12** [comment]
I didn't notice any ill effects. That's part of why I was asking. If there was devilry going on, I could not locate it. The testing file worked as well.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, I can confirm no "ill effects" either. I'd say this issue is resolved!

**Comment by AARON-CLARK** [comment]
closed with #81
