### ISSUE TITLE
Rcheck: installed package size is large

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#72]
![image](https://user-images.githubusercontent.com/17878953/170262664-97cc8ed5-a643-44e7-ae8b-dca2dfbe2a46.png)

I deleted the `doc/` folder on `master` and in the `chk` branch, so I'm not entirely sure why this keeps showing up.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK `pkgdown::build_reference_index()` fails locally for me with the error produced in Github actions. I am using version 2.0.4. What are you using locally?

**Comment by AARON-CLARK** [comment]
closed with #81
