### ISSUE TITLE
Add `OS Health` badge

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#92]
As seen on pkgs here:
https://pharmaverse.org/e2eclinical/tlg/

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK 

Is the goal for these badges to be linked to Github actions?

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, that's a good question. I just checked out Tplyr's github action workflows, and there is nothing in there regarding `OS Health`. Actually, there is nothing I could find in the entire repo regarding `OS Health` (as far as I can tell). 

Doing a little research, it looks like this badge's score came from a package called [`{GithubMetrics}`](https://openpharma.github.io/GithubMetrics/articles/os-health.html) and it looks like the badges are only featured on openpharma.github.io and pharamverse.org.

All that to say - we could create it manually for now (step 1) and explore a GHA workflow later (step 2).

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, some additional thoughts after reviewing the `riskmetric` badge workflow which I found pretty easy after reviewing some example code [here](https://github.com/openpharma/visR/pull/235/files)... This code is pretty concise and easily added to the readme. Not sure if it justifies an entirely new script but I'm open to seeing what you've got. OS health does seem a little more... involved.

To my knowledge the `pkgdown` GHA workflow runs `build_site()`, which doesn't re-build the `readme.md` file. But it looks like there exists a function called `devtools::build_readme()` which could be added to our `pkgdown` workflow before `build_site()` launches? More info on `build_readme()`: https://devtools.r-lib.org/reference/build_rmd.html

**Comment by Jeff-Thompson12** [comment]
I'm open to discussion on how we want to proceed. I was going to blatantly utilize the badge creation [code](https://github.com/openpharma/openpharma.github.io/blob/master/scripts/generate-badges.R) employed by openpharma.

I was going to implement the scripts within the README.Rmd file, so the README.md file would actually be static. It would just require us to periodically re-knit the file.

Making the actual badges dynamic and connected to Github Actions seems to be a bit more [involved](https://schneegans.github.io/tutorials/2022/04/18/badges).

**Comment by AARON-CLARK** [comment]
closed with #128
