### ISSUE TITLE
Reincorporate a Vignette for CRAN

### ISSUE THREAD

**Issue by Jeff-Thompson12** [Biogen-Inc/tidyCDISC#96]
Working on more simplified versions of the current vignettes to be included for submission to CRAN.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, now that I'm looking at this, didn't we decide that the README on `for_cranny` was sufficient to help users get plugged in to the `pkgdown` documentation? Or do you think having a version of the "Get Started" page will help old school R users who are looking for vignettes on CRAN? I must admit - some people do rely on those... but I'm not sure how many. Eh, nevertheless, I guess it can't hurt. I'll work on creating a 'Get started' vignette for CRAN.

**Comment by Jeff-Thompson12** [comment]
Yes, but when you ran `riskmetric` on `{IDEAFilter]` you realized we would be getting dinged for not having any vignettes. I don't think that incorporating the vignettes is necessary for CRAN submission.

Personally I never browse vignettes in R. I always look for a website.

**Comment by AARON-CLARK** [comment]
> you realized we would be getting dinged for not having any vignettes

Your right. Great memory. I'll try to knock it out quickly. Just using PNGs instead of GIFs

**Comment by AARON-CLARK** [comment]
closed with #81
