### ISSUE TITLE
Security Concern

### ISSUE THREAD

**Issue by Jeff-Thompson12** [Biogen-Inc/tidyCDISC#97]
https://github.com/Biogen-Inc/tidyCDISC/blob/33d7c83054df1691e0c22952811570f4023be376/R/mod_dataUpload.R#L198

This line parses and evaluates text from the interactive environment. The user is actually able to change the text of these values and would be able to run whatever code they wanted. Evaluation is also done [here](https://github.com/Biogen-Inc/tidyCDISC/blob/8eb83c01ecd64a5e31ec50bcca639c76c9ba3e25/R/mod_tableGen.R#L673). It is unclear if this also poses a security risk, but we might want to think about recoding it anyways to be safe.

**Comment by AARON-CLARK** [comment]
This concern is legitimate! We should work towards an alternative.
